name: Release Pipeline

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload Excel file to GitHub Release Page
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v*.*.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./apps/014_Eastern_Region_Pre_processing/mid_year_population_estimates.xlsx
          asset_name: mid_yeay_population_estimates-${{ github.event.release.tag_name }}.xlsx
          asset_content_type: application/zip